name: RepoGallery

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch GitHub Pages and Generate HTML
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ROOT: ${{ github.workspace }}
        run: python scripts/generate_html.py

      - name: Prepare deployment folder
        run: |
          rm -rf public
          mkdir public
          cp index.html public/
          cp -R assets public/
          mkdir -p public/templates
          find templates -type d -name js -exec sh -c 'mkdir -p public/$(dirname {}); cp -R {} public/$(dirname {})' \;
          find templates -type d -name css -exec sh -c 'mkdir -p public/$(dirname {}); cp -R {} public/$(dirname {})' \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
          retention-days: 1

  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
      contents: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: [Update]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
